EXPECTED_TASK_METADATA_SUMMARY = {
    "row_count": 79,
    "family_counts": {
        "CODE_BASED": 21,
        "HASH_BASED": 8,
        "IMPLEMENTATION_SECURITY": 20,
        "ISOGENY_HISTORICAL": 4,
        "LWE": 10,
        "MLWE": 2,
        "MULTIVARIATE": 12,
        "NTRU": 1,
        "SIS": 1,
    },
    "support_level_counts": {
        "implemented": 60,
        "schema_only": 19,
    },
    "seed_evaluation_status_counts": {
        "ok": 59,
        "unsupported": 20,
    },
    "seed_reward_counts": {
        "0.0": 20,
        "1.0": 59,
    },
    "seed_reproduction": {
        "attempted": 42,
        "not_attempted": 37,
        "status_counts": {
            "estimator_reproduced": 1,
            "instance_solved": 41,
            "not_applicable": 28,
            "not_requested": 9,
        },
        "succeeded": 42,
    },
    "seed_estimator_counts": {
        "code-based-placeholder-estimator": 3,
        "hash-based-placeholder-estimator": 1,
        "implementation-security-placeholder-evaluator": 9,
        "isogeny-historical-placeholder-estimator": 1,
        "lattice-family-router": 3,
        "mock-lattice-estimator": 11,
        "multivariate-placeholder-estimator": 3,
        "toy-code-based-bit-flip-decoder-estimator": 3,
        "toy-code-based-circulant-erasure-decoder-estimator": 1,
        "toy-code-based-circulant-syndrome-decoder-estimator": 1,
        "toy-code-based-classic-mceliece-support-syndrome-estimator": 1,
        "toy-code-based-classic-mceliece-syndrome-estimator": 1,
        "toy-code-based-erasure-syndrome-decoder-estimator": 1,
        "toy-code-based-isd-estimator": 7,
        "toy-code-based-parity-check-decoder-estimator": 1,
        "toy-code-based-repetition-decoder-estimator": 1,
        "toy-code-based-weighted-repetition-decoder-estimator": 1,
        "toy-hash-bound-estimator": 7,
        "toy-implementation-security-estimator": 11,
        "toy-isogeny-historical-path-estimator": 3,
        "toy-multivariate-estimator": 9,
    },
}
