EXPECTED_FAMILY_SUPPORT_SUMMARY = {
    "benchmark_count": 78,
    "cross_family_review_source_count": 3,
    "families_with_future_reviewed_adapters": [
        "CODE_BASED",
        "HASH_BASED",
        "IMPLEMENTATION_SECURITY",
        "LWE",
        "MLWE",
        "MULTIVARIATE",
        "NTRU",
        "SIS",
    ],
    "family_count": 9,
    "implemented": [
        "LWE",
        "MLWE",
    ],
    "per_family_future_reviewed_adapter_source_counts": {
        "CODE_BASED": 3,
        "HASH_BASED": 1,
        "IMPLEMENTATION_SECURITY": 8,
        "ISOGENY_HISTORICAL": 0,
        "LWE": 2,
        "MLWE": 2,
        "MULTIVARIATE": 1,
        "NTRU": 2,
        "SIS": 2,
    },
    "plugin_count": 6,
    "plugins": [
        "code_based",
        "hash_based",
        "implementation_security",
        "isogeny_historical",
        "lattice",
        "multivariate",
    ],
    "public_example_count": 79,
    "review_required_before_claims": True,
    "schema_only": [
        "NTRU",
        "SIS",
    ],
    "toy_evaluators": [
        "CODE_BASED",
        "HASH_BASED",
        "IMPLEMENTATION_SECURITY",
        "ISOGENY_HISTORICAL",
        "MULTIVARIATE",
    ],
    "support_level_counts": {
        "implemented": 2,
        "schema_only": 2,
        "toy_evaluator": 5,
    },
    "unique_future_reviewed_adapter_source_count": 15,
}
